version: '3.1'

services:

  drupal:
    image: drupal:7-apache
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
      - /var/www/html/sites/default/files
      - ./:/var/www/html/sites/all/modules/hangman
    restart: always
    links:
      - postgres

  postgres:
    image: postgres:9.6
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    expose:
      - 5432
    restart: always
