<?php

/**
 * @file
 * A module that adds a hangman game to Drupal.
 */

require 'functions.php';

/**
* Implements hook_menu().
*/
function hangman_menu() {
    $items = array();
    $items['hangman'] = array(
        'title' => 'Hangman Game',
        'page callback' => '_hangman_page',
        'access arguments' => array('access content')
      );
    $items['hangman/high-scores'] = array(
        'title' => 'Hangman Game High-Scores',
        'page callback' => '_hangman_high_scores_page',
        'access arguments' => array('access content')
      );
    return $items;
}

