<?php

/**
 * @file
 * A module that adds a hangman game to Drupal.
 */

require_once 'lib/display.php';
require_once 'lib/gameplay.php';
require_once 'lib/score.php';

/**
* Implements hook_menu().
*/
function hangman_menu() {
    $items = array();

    $items['hangman'] = array(
        'title' => 'Hangman Game',
        'page callback' => '_hangman_page',
        'access arguments' => array('access content')
      );

    $items['hangman/check-char'] = array(
      'type' => MENU_CALLBACK,
      'access arguments' => array('access content'),
      'page callback' => '_hangman_ajax_check_char',
      'delivery callback' => 'drupal_json_output',
    );

    $items['hangman/save-score'] = array(
      'type' => MENU_CALLBACK,
      'access arguments' => array('access content'),
      'page callback' => '_hangman_ajax_save_score',
      'delivery callback' => 'drupal_json_output',
    );

    $items['hangman/high-scores'] = array(
        'title' => 'Hangman Game High-Scores',
        'page callback' => '_hangman_high_scores_page',
        'access arguments' => array('access content')
      );
    return $items;
}

