<?php

/**
 * @file
 * A module that adds a hangman game to Drupal.
 */

require_once 'lib/display.php';
require_once 'lib/gameplay.php';
require_once 'lib/score.php';
require_once 'lib/admin.php';

/**
* Implements hook_menu().
*/
function hangman_menu() {
    $items = array();

    $items['hangman'] = array(
        'title' => 'Hangman Game',
        'page callback' => '_hangman_page',
        'access arguments' => array('access content')
      );

    $items['hangman/check-char'] = array(
      'type' => MENU_CALLBACK,
      'access arguments' => array('access content'),
      'page callback' => '_hangman_ajax_check_char',
      'delivery callback' => 'drupal_json_output',
    );

    $items['hangman/save-score'] = array(
      'type' => MENU_CALLBACK,
      'access arguments' => array('access content'),
      'page callback' => '_hangman_ajax_save_score',
      'delivery callback' => 'drupal_json_output',
    );

    $items['hangman/high-scores'] = array(
        'title' => 'Hangman Game High-Scores',
        'page callback' => '_hangman_high_scores_page',
        'access arguments' => array('access content')
    );

    $items['admin/hangman/word/add'] = array(
      'title' => 'Add Word',
      'description' => 'Add Hangman Word.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('_hangman_word_form'),
      'access arguments' => array('access hangman_word'),
      'weight' => -14,
    );

    $items['admin/hangman/word/%/edit'] = array(
      'title' => 'Edit Word',
      'description' => 'View Hangman Words.',
      'page callback' => '_hangman_word_edit_block_view',
      'page argument' => array(3),
      'access arguments' => array('access hangman_word'),
      'weight' => -14,
    );

    $items['admin/hangman/word/%/delete'] = array(
      'title' => 'Delete Word',
      'description' => 'delete Hangman Words.',
      'page callback' => '_hangman_word_delete',
      'page argument' => array(3),
      'access arguments' => array('access hangman_word'),
      'weight' => -14,
    );

    $items['admin/hangman/word'] = array(
      'title' => 'Hangman Words',
      'description' => 'View Hangman Words.',
      'page callback' => '_hangman_word_sort_with_pager_content',
      'access arguments' => array('access hangman_word'),
      'weight' => -14,
    );

    return $items;
}

